client_name: LeoTech
project_name: LeoTech website wireframes

github_org: katiebushdesign
github_repo: leotech-wireframes
preview_base_url: https://katiebushdesign.github.io/leotech-wireframes/

copy_doc_url: https://docs.google.com/document/d/1sTTwQXWcxXUdeXufxzzN_xZTBsKwinXvfDIxmYyhH68/edit

copy_docx_path: .wireframe-kit/content/source/copy.docx

marker_project_id: ""
